# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AriaCore < Formula
  desc "ARIA Core — motor de memoria persistente para agentes de IA. Multi-tenant, single binary."
  homepage "https://github.com/ITECHDEV-MX/aria-core"
  version "0.16.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ITECHDEV-MX/aria-core/releases/download/v0.16.0/aria-core_0.16.0_darwin_amd64.tar.gz"
      sha256 "a118efa5e77a7132e90589b3552b78b6d396444ffa18c2d3709e4ca60e7db196"

      define_method(:install) do
        bin.install "aria-core"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ITECHDEV-MX/aria-core/releases/download/v0.16.0/aria-core_0.16.0_darwin_arm64.tar.gz"
      sha256 "35d02d1b6c2152cbbf39b5f04bdf2c7b82c49d92acef20cbe32e3d8097fc1a5a"

      define_method(:install) do
        bin.install "aria-core"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ITECHDEV-MX/aria-core/releases/download/v0.16.0/aria-core_0.16.0_linux_amd64.tar.gz"
      sha256 "26ec91043250fad7b512d6ecf8330606abd3758a3068622e361c988c6e3ca94f"
      define_method(:install) do
        bin.install "aria-core"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ITECHDEV-MX/aria-core/releases/download/v0.16.0/aria-core_0.16.0_linux_arm64.tar.gz"
      sha256 "bb59296a7e00a100307fadfc45bc91f19e42e9c621b73fbb80a06eae4b8d94e2"
      define_method(:install) do
        bin.install "aria-core"
      end
    end
  end

  test do
    assert_match "aria-core", shell_output("#{bin}/aria-core --version")
  end
end
